<?php
$year  = (int)($_GET['year']  ?? date('Y'));
$month = (int)($_GET['month'] ?? date('n'));
$report = getMonthlySummary($year, $month);
$monthName = date('F Y', mktime(0,0,0,$month,1,$year));
?>
<div class="page-header">
    <div class="flex-between">
        <div>
            <h2><i class="fas fa-file-export"></i> Monthly Summary Report</h2>
            <p>Platform activity snapshot for a selected month</p>
        </div>
        <button class="btn btn-ghost btn-sm" onclick="window.print()"><i class="fas fa-print"></i> Print / Export</button>
    </div>
</div>


<div class="card" id="no-print">
    <h3><i class="fas fa-calendar"></i> Select Period</h3>
    <form method="GET" style="display:flex;gap:12px;align-items:flex-end;flex-wrap:wrap;">
        <input type="hidden" name="page" value="report">
        <div class="form-group" style="margin:0;">
            <label>Year</label>
            <select name="year">
                <?php for ($y = date('Y'); $y >= 2020; $y--): ?>
                <option value="<?= $y ?>" <?= $year==$y?'selected':'' ?>><?= $y ?></option>
                <?php endfor; ?>
            </select>
        </div>
        <div class="form-group" style="margin:0;">
            <label>Month</label>
            <select name="month">
                <?php for ($m = 1; $m <= 12; $m++): ?>
                <option value="<?= $m ?>" <?= $month==$m?'selected':'' ?>><?= date('F', mktime(0,0,0,$m,1)) ?></option>
                <?php endfor; ?>
            </select>
        </div>
        <button type="submit" class="btn btn-primary btn-sm"><i class="fas fa-chart-bar"></i> Generate</button>
    </form>
</div>


<div id="printable">
<div class="card">
    <div style="text-align:center;margin-bottom:24px;padding-bottom:18px;border-bottom:1px solid var(--border);">
        <h2 style="font-size:24px;color:var(--accent);">JobPortal Platform</h2>
        <h3 style="font-size:16px;color:var(--text);margin-top:6px;">Monthly Summary Report — <?= $monthName ?></h3>
        <p style="color:var(--muted);font-size:12px;margin-top:4px;">Generated on <?= date('d F Y H:i') ?></p>
    </div>

   
    <h4 style="color:var(--accent);margin-bottom:14px;font-size:13px;text-transform:uppercase;letter-spacing:1px;">New Registrations</h4>
    <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:14px;margin-bottom:28px;">
        <?php
        $roleColors = ['seeker'=>'var(--blue)','employer'=>'var(--green)','recruiter'=>'var(--purple)','admin'=>'var(--accent)'];
        $roleIcons  = ['seeker'=>'fa-user','employer'=>'fa-building','recruiter'=>'fa-headset','admin'=>'fa-shield-halved'];
        foreach (['seeker','employer','recruiter','admin'] as $role):
            $count = $report['new_users'][$role] ?? 0;
        ?>
        <div style="background:var(--bg3);border-radius:10px;padding:16px;text-align:center;border:1px solid var(--border);">
            <i class="fas <?= $roleIcons[$role] ?>" style="font-size:22px;color:<?= $roleColors[$role] ?>;margin-bottom:8px;display:block;"></i>
            <div style="font-size:24px;font-weight:700;color:<?= $roleColors[$role] ?>;"><?= $count ?></div>
            <div style="font-size:11px;color:var(--muted);margin-top:4px;"><?= ucfirst($role) ?>s</div>
        </div>
        <?php endforeach; ?>
    </div>

   
    <h4 style="color:var(--accent);margin-bottom:14px;font-size:13px;text-transform:uppercase;letter-spacing:1px;">Activity Summary</h4>
    <div class="table-wrap" style="margin-bottom:24px;">
        <table>
            <thead><tr><th>Metric</th><th>Count</th></tr></thead>
            <tbody>
                <tr><td>New Job Postings</td><td><strong><?= $report['new_jobs'] ?></strong></td></tr>
                <tr><td>New Applications</td><td><strong><?= $report['new_apps'] ?></strong></td></tr>
                <tr><td>New Complaints Filed</td><td><strong><?= $report['new_complaints'] ?></strong></td></tr>
                <tr><td>Total New Users</td><td><strong><?= array_sum($report['new_users']) ?></strong></td></tr>
            </tbody>
        </table>
    </div>

    <p style="font-size:11px;color:var(--muted);text-align:center;margin-top:10px;">
        This report was automatically generated by JobPortal Admin Panel. Data reflects activity within <?= $monthName ?>.
    </p>
</div>
</div>

<style>
@media print {
    #no-print, .sidebar, aside { display: none !important; }
    .main-content { margin-left: 0 !important; }
    body { background: #fff; color: #000; }
    .card { border: 1px solid #ddd; box-shadow: none; }
}
</style>
